root: true
env:
  jest: true
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - '@vue/standard'
  - './.eslintrc-auto-import.json'
overrides: []
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jax: true
  extraFileExtensions:
    - '.vue'
  project:
    - './tsconfig.json'
    - './tsconfig.node.json'
plugins:
  - '@typescript-eslint'
  - prettier
  - vue
rules:
  prettier/prettier: error
