// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiGoogle: typeof import('~icons/mdi/google')['default']
    IMdiWechat: typeof import('~icons/mdi/wechat')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VginIcon: typeof import('./../components/VginIcon/index.vue')['default']
    VIcon: typeof import('./../components/VIcon/index.vue')['default']
  }
}
